#example data
# lat = 50.84050277777778 #weather station caldern
# lon = 8.683303333333333 #weather station caldern
# elev = 270 #weather station caldern
# surface_type = "Wiese"  #weather station caldern
# obs_height = 0.3
# texture = "clay" #needed when soil_flux unknown
# valley = F
# slope = NULL #if not NULL, the rad_bal with topography will be calculated
# z1 = 2
# z2 = 10
# depth1 = NULL #needed when soil_flux unknown
# depth2 = NULL #needed when soil_flux unknown
# datetime = c(1,2,3,4,5,6,7,8)
# t1 = c(1,2,3,4,5)
# t2 = c(4,5,7,78,2)
# v1 = c(1,23,4,6,23)
# v2 = c(2,4,6,4,2,4,6)
# hum1 = c(2,4,6,4,2,4,6)
# hum2 = c(2,4,6,4,2,4,6)
# p1 = NULL
# p2 = NULL
# rad_bal = NULL #if NULL -> will be calculated, albedo needed
# sw_bal = NULL#if NULL -> will be calculated, albedo needed
# lw_bal = NULL#if NULL -> tough luck, won't be calculated
# albedo = NULL #needed, if radiation balance is unknown an shall be calulated
# soil_flux = NULL
# ts1 = NULL
# ts2 = NULL
# moisture = NULL

# testomat <- build_weather_station(lat = 50.84050277777778, #weather station caldern
#                                   lon = 8.683303333333333, #weather station caldern
#                                   elev = 270, #weather station caldern
#                                   surface_type = "Wiese",  #weather station caldern
#                                   obs_height = 0.3,
#                                   texture = "clay", #needed when soil_flux unknown
#                                   valley = F,
#                                   slope = NULL, #if not NULL, the rad_bal with topography will be calculated
#                                   z1 = z1,
#                                   z2 = z2,
#                                   depth1 = NULL, #needed when soil_flux unknown
#                                   depth2 = NULL, #needed when soil_flux unknown
#                                   datetime = datetime,
#                                   t1 = t1,
#                                   t2 = t2,
#                                   v1 = v1,
#                                   v2 = v2,
#                                   hum1 = hum1,
#                                   hum2 = hum2,
#                                   p1 = NULL,
#                                   p2 = NULL,
#                                   rad_bal = NULL, #if NULL -> will be calculated, albedo needed
#                                   sw_bal = NULL, #if NULL -> will be calculated, albedo needed
#                                   lw_bal = NULL, #if NULL -> tough luck, won't be calculated
#                                   albedo = NULL, #needed, if radiation balance is unknown an shall be calulated
#                                   soil_flux = NULL,
#                                   ts1 = NULL,
#                                   ts2 = NULL,
#                                   moisture = NULL)
